import datetime,hashlib,json,subprocess,time
from pathlib import Path
root=Path('/private/tmp/mcp-phase22-options');b=root/'artifacts/phase22/integration';run=lambda a:subprocess.check_output(a,cwd=root,text=True);sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda n:json.loads((b/n).read_text())
def write(name,data):
 p=b/name;assert not p.exists(),name;p.write_text(json.dumps(data,indent=2)+'\n')
head=read('v22-final-candidate.json')['candidate'];assert run(['git','rev-parse','HEAD']).strip()==head
inputs=['src','tests','scripts','.github','schemas','Makefile','pyproject.toml','uv.lock','action.yml','README.md','LICENSE','CHANGELOG.md','THIRD_PARTY_NOTICES.md','.pre-commit-hooks.yaml','.python-version','.gitattributes','demo','sentinel.toml'];assert not run(['git','diff','HEAD','--',*inputs])
for label in ['v22-verification-command','v22-closeout-command','v22-final-docs-check']:assert read(label+'.json')['exit_code']==0,label
assert read('v22-final-quality/packet.json')['engineering_passed'] and read('v22-final-quality/packet.json')['source']==head
fields='number,state,isDraft,title,headRefName,headRefOid,baseRefName,body';before=json.loads(run(['gh','pr','view','37','--json',fields]));parent=json.loads(run(['gh','pr','view','36','--json','headRefOid,headRefName']))
assert before['headRefOid']==head and before['isDraft'] and before['state']=='OPEN' and before['baseRefName']=='phase22/description-poisoning';assert before['body']==(b/'v21-closeout-draft-body.md').read_text();assert parent['headRefOid']=='8b6b0ddf1d6f6cf5a8da3ab9421471865b801455';subprocess.run(['git','merge-base','--is-ancestor',parent['headRefOid'],head],cwd=root,check=True)
docs=list(read('v21-final-documentation-binding.json')['final_documents_sha256']);subprocess.run(['git','diff','--check','--',*docs],cwd=root,check=True)
check=read('v22-final-docs-check.json');assert sha(b/'v22-final-docs-check.patch')==check['diff_sha256'];seal=read('evidence-v51.json');assert sha(b/seal['archive'])==seal['sha256']
measurements=read('v22-refresh-disposition-corrected.json')['total_attempts_consumed'];fresh=read('v21-fresh-proposal-verification.json');assert all(sha(root/n)==d for n,d in fresh['prepared_files_sha256'].items())
binding={'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'hosted_source':head,'local_full_suite_source':'1f3f72f0f25c597b53c9f833e2e4bec99728d328','scanner':read('v22-source-verification.json')['scanner'],'actual_exposed_measurement_source':'2ac39aa9331818fd7e3a86c8323ee8307522c98c','actual_sequence_scanner':'1f3f72f0f25c597b53c9f833e2e4bec99728d328','final_documents_sha256':{n:sha(root/n) for n in docs},'delivery_helper_sha256':sha(b/'v22-final-delivery-helper.py'),'audit_sha256':sha(b/'v22-closeout-audit/packet.json'),'evidence_manifest_sha256':sha(b/'evidence-v51.json'),'evidence_archive_sha256':seal['sha256'],'proposal_sha256':sha(root/'artifacts/phase22/corpus-replacement-v4/evaluation-proposal.json'),'approved_refresh_proposal_sha256':sha(b/'v21-historical-assessment-refresh-proposal.json'),'approval_sha256':sha(b/'v22-refresh-authorization.json'),'draft_body_sha256':sha(b/'v22-closeout-draft-body.md'),'docs_check_sha256':sha(b/'v22-final-docs-check.json'),'binding':'Current code/test/workflow/package inputs equal the tested final candidate. Scanner/test/package bytes remain1f3f72f. Current document hashes supersede audit-stage hashes only. Documentation/evidence-only delivery uses authorized CI skip and is not a new hosted code pass.','new_corpus_runs':measurements,'new_paid_calls':0,'fresh_evaluation_approved':False,'phase22_complete':False}
write('v22-final-documentation-binding.json',binding)
write('v22-delivery-verification.json',{'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'delivery_parent':head,'tested_source':head,'remote_before':before,'parent_before':parent,'tested_inputs_identical_to_candidate':inputs,'documents':docs,'binding_sha256':sha(b/'v22-final-documentation-binding.json'),'raw_docs_patch_sha256':check['diff_sha256'],'archive_sha256':seal['sha256'],'scope_amendment_approved':True,'new_corpus_runs':measurements,'new_paid_calls':0,'phase22_complete':False,'delivery_binding':'Binds verified pre-commit tree. Resulting commit and remote readback are a supplemental local receipt; no self-referential hash.'})
core=['evidence-v51.json','evidence-v51.tar.gz','v22-final-delivery-helper.py','v22-preparatory-candidate.json','v22-final-candidate.json','v22-preparatory-run.json','v22-final-run.json','v22-refresh-disposition-corrected.json','v22-assessment-freeze.json','v22-preparatory-source-deltas/packet.json','v22-kubernetes-mutation-source-assessment.json','v22-source-verification.json','v22-closeout-audit/packet.json','v22-closeout-summary.md','v22-closeout-draft-body.md','v22-final-documentation-binding.json','v22-delivery-verification.json']+[f'{label}.{suffix}' for label in ['v22-closeout-command','v22-final-docs-check'] for suffix in ['json','log','patch','untracked.tar.gz']]
subprocess.run(['git','add','--',*docs],cwd=root,check=True);subprocess.run(['git','add','-f','--',*[str((b/n).relative_to(root)) for n in core]],cwd=root,check=True)
allowed=set(docs)|{str((b/n).relative_to(root)) for n in core};staged=set(run(['git','diff','--cached','--name-only']).splitlines());assert staged<=allowed,staged-allowed
subprocess.run(['git','diff','--cached','--check','--','.',':(exclude)artifacts/phase22/integration/*.patch'],cwd=root,check=True);subprocess.run(['git','commit','-m','Seal approved historical assessment refresh and final gate evidence [skip ci]'],cwd=root,check=True)
delivery=run(['git','rev-parse','HEAD']).strip();assert not run(['git','diff',head,delivery,'--',*inputs]);subprocess.run(['git','push','origin','phase22/integration'],cwd=root,check=True);subprocess.run(['gh','pr','edit','37','--body-file',str(b/'v22-closeout-draft-body.md')],cwd=root,check=True)
for attempt in range(12):
 after=json.loads(run(['gh','pr','view','37','--json',fields]))
 if after['headRefOid']==delivery and after['body']==(b/'v22-closeout-draft-body.md').read_text():break
 time.sleep(3)
assert after['headRefOid']==delivery and after['body']==(b/'v22-closeout-draft-body.md').read_text() and after['isDraft'] and after['state']=='OPEN' and after['baseRefName']==before['baseRefName'];assert not run(['git','diff','HEAD'])
prompts=read('v22-refresh-authorization.json')['user_files_sha256'];assert set(run(['git','ls-files','--others','--exclude-standard']).splitlines())==set(prompts)
for n,d in prompts.items():assert sha(root/n)==d
for n,d in binding['final_documents_sha256'].items():assert sha(root/n)==d
write('v22-final-delivery-readback.json',{'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'delivered_head':delivery,'tested_source':head,'remote_after':after,'verification_sha256':sha(b/'v22-delivery-verification.json'),'binding_sha256':sha(b/'v22-final-documentation-binding.json'),'tested_inputs_equal':True,'tracked_worktree_clean':True,'user_files_preserved':prompts,'new_corpus_runs':measurements,'new_paid_calls':0,'phase22_complete':False,'storage':'Supplemental ignored local post-delivery receipt; tracked/sealed evidence is the delivered Git tree.'});print(delivery)
