"""Close the approved source-only attempt and retain every check/failure distinction."""
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
OUT=Path(__file__).resolve().parent;BASE=OUT.parent
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
local=read(OUT/'local-checks.json');quality=read(BASE/'v66-candidate-quality-audit/packet.json');freeze=read(OUT/'freeze.json')
assert local['states']=={'passed':2419,'skipped':36} and len(quality['quality'])==12
assert read(OUT/'source-proof.json')['exact_prior_candidate_reapplied']
for name in ['equivalence','production-flow-equivalence','production-boundaries','report-equivalence','five-rule-report-equivalence','discovery-equivalence','guard-validation','helper-control-result']:assert read(OUT/(name+'.json'))['passed'],name
expected={'v66-full-suite':1,'v66-production-flow':1,'v66-report-equivalence':1,'v66-lock':2,'v66-build':2,'v66-production-boundaries':1,'v66-production-boundaries-corrected':1}
failed={f.stem:read(f)['exit_code'] for f in BASE.glob('v66-*.json') if 'exit_code' in read(f) and read(f)['exit_code']!=0};assert failed==expected,failed
corrections={
 'v66-full-suite':'The original full run retained2415 passed,36 skipped and four loopback HTTP fixture failures: PermissionError at socket.bind before the assertions. The entire2455-test collection was rerun at identical4145d35 source with authorized loopback access, producing2419 passed/36 skipped. No product/test change or model service call. Earlier progress updates inferred no failures from the current tail and were incomplete; the final full result and four original failures are retained explicitly.',
 'v66-production-flow':'Python deepcopy shares functions: the injected test callback closure retained a bound method pointing at the original flow, so reference execution mutated the candidate input. The retained identical-baseline negative control reproduces the mismatch with no implementation difference. Corrected closure cells bind the copied flow and compare closure fields too; all263 tests/766 full-state comparisons pass. No failing product state was excluded.',
 'v66-report-equivalence':'Absolute helper execution lacked repository root for tests.conftest. Add only that explicit root; all10 worker tests and six complete baseline-versus-candidate results pass.',
 'v66-lock':'Existing uv cache access was denied by sandbox before dependency resolution. Same offline locked check passes with authorized cache access; no lock/dependency change.',
 'v66-build':'Existing uv cache access was denied before build. Same offline build passes with authorized cache access; candidate archive members bind actual source.',
 'v66-production-boundaries':'The synthetic interpreter deadline1e99 overflowed the subprocess timeout converter during owned AST parsing. Use a finite30-second parsing deadline; interpreter-only synthetic deadline remains finite and has no subprocess.',
 'v66-production-boundaries-corrected':'The unknown-call fixture initially used primitive Values, which do not trigger object-escape invalidation. Existing production code explicitly invalidates object/instance/class/array/schema/HTTP values. Mark the intended left/right controls as objects in both references; all252 complete comparisons and conservative invalidations pass. No implementation difference was excluded.'}
(OUT/'check-failure-assessment.json').write_text(json.dumps({'failed_wrapper_checks':failed,'corrections':corrections,'read_only_status_command_correction':'One inline progress-counter read had an unmatched parenthesis; the corrected read succeeded. It changed no files or product state.', 'preexecution_preparation_correction':'Review caught a mechanical row-count replacement touching sha256 names in the not-yet-executed reconciliation helper. The unexecuted draft is preserved; the corrected helper retains SHA-256 throughout.', 'nested_expected_negative_control':'The initial callback-copy helper fails with identical baseline methods; this expected helper negative control is retained inside its passing wrapper.','report_scope_correction':'The original six worker-report comparisons selected four FLOW_RULES. Their initial five-rule wording is retained and corrected without altering outcomes; six additional full reports explicitly select SENT-012 through016 and pass.', 'old_v65_strict_failure':'Remains failed and unresolved. Exact alias/shrink deltas are reproduced unchanged; only the explicit prospective classification was approved.','paid_calls':0},indent=2)+'\n')
budget={'recorded_at':datetime.now(timezone.utc).isoformat(),'attempted':1,'passed':1,'failed':0,'remaining':0,'closed':True,'source_only':True,'candidate':freeze['scanner'],'authorization_sha256':sha(OUT/'authorization.json'),'corpus_observations':0,'profiles':0,'paid_calls':0,'qualification':'Engineering-verified source-only attempt. No native speedup, completion, detection or compatibility gate inferred. All earlier budgets remain closed.'}
(OUT/'optimization-budget-closed.json').write_text(json.dumps(budget,indent=2)+'\n')
assessment={'passed':True,'scanner':freeze['scanner'],'source_only_attempt':budget,'approved_revision':read(OUT/'authorization.json')['prospective_contract_revision'],'ordinary_comparisons':256,'complete_production_flow_comparisons':766,'production_boundary_comparisons':252,'ordered_discovery_comparisons':125,'complete_five_rule_serial_parallel_report_comparisons':6,'additional_four_worker_report_comparisons':6,'mutation_guard_negative_controls':5,'original_failed_attempt_remains_unresolved':True,'exact_two_negative_control_deltas_retained':True,'no_other_counterexample_excluded':True,'engineering_inputs':303,'evidence_sha256':{n:sha(OUT/n) for n in ['source-proof.json','production-domain-proof.json','equivalence.json','production-flow-equivalence.json','production-boundaries.json','discovery-equivalence.json','report-equivalence.json','five-rule-report-equivalence.json','guard-validation.json','helper-control-result.json','local-checks.json','compatibility.json','freeze.json','check-failure-assessment.json']},'engineering_quality_sha256':sha(BASE/'v66-candidate-quality-audit/packet.json'),'native_speedup_established':False,'current_source_corpus_compatibility_established':False,'current_source_corpus_observations':0,'profiles':0,'paid_calls':0,'technical_acceptance_received':False,'phase22_complete':False}
(OUT/'assessment.json').write_text(json.dumps(assessment,indent=2)+'\n')
print('One source-only attempt passed and closed; historical strict failure and all corrected checks retained.')
