"""Bind exact source, runner, order and finite numerical scope; no authorization."""
import hashlib,json,sys
from datetime import datetime,timezone
from pathlib import Path
OUT=Path(__file__).resolve().parent;ROOT=OUT.parents[3];BASE=ROOT/'artifacts/phase22/corpus-unseen-v1'
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):
 with p.open('x') as f:json.dump(d,f,indent=2);f.write('\n')
freeze=read(OUT/'scope-and-precuration-freeze.json');checkpoint=read(BASE/'checkpoint-cec0322.json');manifest=read(BASE/'manifest.json');configs=read(BASE/'configurations.json');cases=read(OUT/'cases.json')
assert read(OUT/'runner-boundaries.json')['passed'] and read(OUT/'collection-checks.json')['passed']
selection={'recorded_at':datetime.now(timezone.utc).isoformat(),'precuration_freeze_sha256':sha(OUT/'scope-and-precuration-freeze.json'),'selected':[c['repository'] for c in cases],'count_justification':'Two distinct cases cover both requested languages and different boundaries: TypeScript shell interpolation to argv, Python local file upload confinement through module dispatch/imported client/helper. Both have actual upstream first-parent fix pairs. This is the smallest justified check in the approved 2–4 range; 6 source records twice yield12 observations/6 entire ordered pairs, not12 independent discoveries.','screened_not_selected':{'ManiaSacha/Astro-mcp':'Inspected fix protects Express REST endpoints, not a source-established registered MCP tool invocation.','zzambers/resultsview':'Inspected security fix is Java, outside the requested languages.','dankez/mcp-therion':'Inspected Python source has a plausible path fix but the archive contains no license declaration/full license; not selected.'},'metadata_only':'Other search results are retained in path-fixes/path-boundary/shell-boundary/python-path/python-shell JSON; metadata mentions alone are distinguished from inspected code. The parent commit metadata for selected repositories also exposes its included patches and remains retained.','license_and_language_qualifications':[c['license_assessment'] for c in cases]+[cases[0]['limits'][1]],'source_research_files_sha256':{str(p.relative_to(ROOT)):sha(p) for p in sorted((OUT/'research').rglob('*')) if p.is_file()},'web_search':{'queries':['site.github.com MCP server security advisory path traversal Python fixed','site.github.com MCP server security advisory command injection TypeScript fixed'],'selected_from_web_results':False,'relevant_result_urls':['https://github.com/modelcontextprotocol/servers/security/advisories','https://github.com/advisories/GHSA-3q26-f695-pp76','https://github.com/advisories/GHSA-fjwc-hc62-p8h9','https://github.com/advisories/GHSA-gjv4-ghm7-q58q'],'qualification':'Search snippets only; selected pair conditions derive from fully retained upstream API/archive sources, not web snippets.'},'model_training_novelty_claim':False,'independent_review':False,'observations':0,'paid_calls':0,'target_execution':False}
write(OUT/'selection-record.json',selection)
stop='Cancellation or identity/infrastructure/execution/timeout/schema/cleanup/entire-ordered-repeat failure stops and closes all unused budget. Named detection misses, false alerts and unsupported negatives are retained failed gates while remaining approved collection continues. No tuning, retries, replacement, profiles or extra observations.'
rubric={'status':'proposed_not_approved_not_executed','cases':cases,'success':'Every named vulnerable condition detected on both passes; zero matching fixed/safe alerts with actual source-supported caller/guard/value/sink qualification; complete valid outputs within all bounds; all6 entire ordered repeats equal. Report per-repository gates and all support/completion/detection denominators. No population accuracy threshold.','full_source_assessment':'Assess every finding including unmatched candidates, every diagnostic, unresolved flow/surface, support denominator and full ordered difference against frozen source. File-only attribution where no literal source location exists. Raw candidates remain, even if unrelated to named conditions. Quiet unsupported negatives fail. Native output has no positive per-sink guard trace; combine truthful report/source evidence without inventing one.','safe_controls':'Each safe record uses the complete corresponding upstream fixed tree/configuration and its own illustrative caller value. Static analysis is not specialized to that value; shared variants/repeats are correlated.','collection_stop':stop,'paid_calls':0,'target_execution':False,'technical_acceptance_received':False}
write(OUT/'scoring-rubric.json',rubric)
inputs=checkpoint['input_order'];groups={};witnesses={}
for case in cases:
 ids=[i for i in inputs if i.startswith(case['id']+'-')]
 groups[case['id']]={'actual_language':case['language'],'repository':case['repository'],'manifest':str((BASE/'manifest.json').relative_to(ROOT)),'manifest_sha256':sha(BASE/'manifest.json'),'source_freeze_approval':'source-freeze-authorization.json','input_ids':ids,'inputs':{i:{'input':next(x for x in manifest['inputs'] if x['id']==i),'configuration_sha256':configs[i]['sha256']} for i in ids}}
 for i in ids:witnesses[i]={'rule_id':case['rule_id'],**case['witnesses']['vulnerable' if i.endswith('-vulnerable') else 'fixed']}
order=[{'group':g,'input_id':i,'batch':batch} for batch in ['first','repeat'] for g,row in groups.items() for i in row['input_ids']]
assert len(order)==12 and len(inputs)==6
bounds={'native_observations':12,'repository_cases':2,'distinct_input_records':6,'entire_ordered_pairs':6,'attempts_per_slot':1,'whole_input_maximum_seconds':1800,'native_maximum_seconds':1800,'cleanup_maximum_seconds':15,'semgrep_rule_timeout_seconds':10,'maximum_existing_flow_workers_per_input':4,'simultaneous_inputs':1,'target_seconds':120,'sequence_maximum_minutes':380,'internal_stop_minutes':378,'input_and_cleanup_component_seconds':21780,'setup_identity_selfcheck_reserve_seconds':900,'finalization_reserve_seconds':120,'outer_supervisor_cleanup_seconds':15,'total_outer_with_cleanup_maximum_seconds':22815,'paid_calls':0,'retries':0,'profiles':0,'comparator_observations':0,'target_executions':0}
files={}
for p in [*BASE.rglob('*'),*OUT.glob('*.py'),OUT/'cases.json',OUT/'selection-record.json',OUT/'scope-and-precuration-freeze.json',OUT/'preparation-baseline.json',OUT/'workspace-inventory.json',OUT/'prior-exposure-inventory.json',OUT/'novelty-comparison.json',OUT/'scoring-rubric.json',OUT/'runner-boundaries.json',OUT/'collection-checks.json',OUT.parent/'v43-four-fresh-preparation/runner.py',OUT.parent/'v20-linux-diagnostic-v1/runner.py']:
 if p.is_file():files[str(p.relative_to(ROOT))]=sha(p)
for p in (OUT/'research').rglob('*'):
 if p.is_file():files[str(p.relative_to(ROOT))]=sha(p)
for n,d in read(OUT.parent/'v72-prototype-property-correction/local-checks.json')['candidate_engineering_files_sha256'].items():assert sha(ROOT/n)==d;files[n]=d
p={'status':'prepared_not_approved_not_executed','recorded_at':datetime.now(timezone.utc).isoformat(),'purpose':selection['count_justification'],'scanner':freeze['scanner'],'frozen_checkout':freeze['frozen_worktree'],'lock_sha256':freeze['lock_sha256'],'runtime':read(OUT/'preparation-baseline.json')['versions'],'python':read(OUT/'preparation-baseline.json')['python'],'manifest':checkpoint['manifest'],'checkpoint':{'path':str((BASE/'checkpoint-cec0322.json').relative_to(ROOT)),'sha256':sha(BASE/'checkpoint-cec0322.json')},'groups':groups,'input_order':inputs,'order':order,'witnesses':witnesses,'bounds':bounds,'volatile_exclusions':['applied_at','completed_at','duration_ms','execution_latency_ms','finding_id','latency_ms','origin_latency_ms','reviewed_at','scan_id','started_at','timestamp'],'stop':stop,'bound_basis':'12 x(1800+15)=21780seconds/363minutes; plus900seconds setup/identity/synthetic reserve=378-minute internal stop; plus120seconds finalization=380-minute outer process limit; outer supervisor retains separate15-second cleanup (total22815seconds/380m15s). Worst-case bound, not duration estimate. Each child starts only if its full1815seconds fit; its clock starts before Popen, imports, materialization, analysis and reporting. Source-only staging/preflight is completed before the timed launch; child revalidation is within the input deadline.','gate':rubric['success'],'prepared_command':[sys.executable,'-I',str(OUT/'evaluate.py'),'run',str(OUT.parent/'v78-unseen-results/raw')],'launch_command':[sys.executable,'-I',str(OUT/'launch.py')],'prepared_command_cwd':freeze['frozen_worktree'],'files_sha256':files,'not_authorized':['any new paid/model call','target execution/import/build/test/install','extra source/replacement/observation','retry/profile/comparator','tuning between fresh inputs','resource/worker change','normal timeout revision','V68 optimization','Phase22 technical acceptance','merge/ready/release/outreach/Phase23'],'freshness_limits':selection['metadata_only']+' Same-agent source curation, project-record novelty only; no independent human or training-data novelty claim.','technical_acceptance_received':False,'phase22_complete':False,'paid_calls':0}
write(OUT/'evaluation-proposal.json',p)
write(OUT/'launcher-binding.json',{'proposal_sha256':sha(OUT/'evaluation-proposal.json'),'launcher_sha256':sha(OUT/'launch.py'),'runner_sha256':sha(OUT/'evaluate.py'),'corpus_adapter_sha256':sha(OUT/'corpus.py'),'command':p['launch_command'],'approved':False,'executed':False,'paid_calls':0})
print('Prepared proposal',sha(OUT/'evaluation-proposal.json'),'2repositories/6inputs/12observations; approval absent.')
