"""Bind the full reviewed result to a separate explicit human acceptance decision."""
import copy,hashlib,json
from pathlib import Path
OUT=Path(__file__).resolve().parent;BASE=OUT.parent;ROOT=OUT.parents[3]
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
a=read(OUT/'audit.json');assert read(OUT/'final-checks.json')['passed'] and a['acceptance_packet_ready'] and not a['technical_acceptance_received'];fresh=read(BASE/'v80-unseen-results/final-assessment/assessment.json')
p=copy.deepcopy(read(BASE/'v76-technical-acceptance/acceptance-proposal.json'))
limits=[{'id':r['id'],'requirement':r['requirement'],'assessment':r['assessment'],'evidence':r['evidence']} for r in a['requirements']+a['additional_scope_requirements'] if r['disposition']=='proposed documented limitation awaiting decision'];assert len(limits)==26
review=[OUT/name for name in ['audit.json','summary.md','acceptance-limits.md','prior-row-preservation.json','status.md','final-checks.json','final-distributions.json','command-provenance.json','check-failure-assessment.json','owned-final.json']]
review += [BASE/'v80-unseen-results'/name for name in ['completion-verification.json','raw/packet.json','execution.json','final-assessment/assessment.json','final-assessment/validation.json','final-assessment/inventory.json','final-assessment/decisive-source-review.json','final-assessment/complete-report-differences.jsonl.gz']]
review += [BASE/'v80-unseen-results/final-assessment'/name for name in fresh['assessment_files_sha256']]
review += [BASE/'v79-unseen-metadata-correction'/name for name in ['evaluation-proposal.json','evaluation-authorization.json','source-freeze-authorization.json','execution-preflight.json','execution-consumed.json','identity-correction-verification.json','delivery-verification.json']]
review += [BASE/'v78-unseen-results/stop-assessment.json',BASE/'v76-technical-acceptance/acceptance-proposal.json',BASE/'v77-unseen-preparation/scope-and-precuration-freeze.json',BASE/'v77-unseen-preparation/selection-record.json']
p['review_files_sha256'].update({str(path.relative_to(ROOT)):sha(path) for path in review})
p.update(requirements=448,proposed_limitation_dispositions=limits,proposed_decision='Accept Phase22 technical completion under the explicitly revised scope permitting the new Proxmox failed vulnerable detection and unsupported fixed/safe paths, the initial V78metadata preparation failure, all26enumerated historical/practical limitation rows and retained deferrals. Accept only narrow Taskwarrior shell discrimination with unresolved metadata/dispatch/parse qualifications. Leave computed Proxmox module-table dispatch unsupported for this closeout and V68performance unopened/unimplemented; no fix or full fresh pass is claimed. Then record the exact human decision and deliver/verify accepted closeout to the same OPEN DRAFT PR37.')
p['new_unseen_results']={'scanner':fresh['scanner'],'repository_cases':2,'input_records':6,'observations_completed':12,'entire_ordered_pairs_equal':6,'cases':fresh['cases'],'all_requested_fresh_gates_passed':False,'whole_input_seconds_min':fresh['whole_input_seconds_min'],'whole_input_seconds_max':fresh['whole_input_seconds_max'],'normal_input_seconds':1800,'semgrep_seconds':10,'cleanup_seconds':15,'workers_max':4,'outer_minutes':380,'findings':4,'diagnostics':504,'surfaces':12,'source_contexts':18,'full_ordered_comparisons':14,'same_agent_source_assessment':True,'independent_human_validation':False,'first_scanner_reports_on_unchanged_first_frozen_sources':True,'source_tuning':False}
p['initial_unseen_failure']={'attempted':1,'incomplete':1,'reports':0,'unstarted_closed':11,'remaining':0,'analysis_started':False,'cause':'Raw proposal omitted parent/overlay/transformation null defaults; strict validated metadata equality failed. Original failure remains failed after complete serialization correction.','accepted':False}
p['preserved_limits'] += ['New Proxmox failed gate: zero of two vulnerable detections, zero of four supported negatives, computed dispatcher remains unsupported. No quiet-negative safety or whole-repository coverage claim.','Taskwarrior has narrow source-supported shell discrimination only; aggregate surface/name/schema remains unresolved, safeParse warnings retained and add_task findings remain unmatched review candidates.','Taskwarrior full MIT and missing direct zod dependency; Proxmox declaration-only MIT. All startup, fixed-tree safe-control, operator-root, no-race and shell-platform assumptions remain. Same-agent project-record source novelty is not independent review or model-training novelty.','Initial V78metadata failure and closed budget remain distinct from12complete V80outputs. No new scanner failure is erased by preparation correction.']
p['budget']={'scopes':{'V73':{'completed':24,'pairs':12,'closed':True,'remaining':0},'V75':{'completed':181,'pairs':83,'closed':True,'remaining':0},'V78':{'attempted':1,'incomplete':1,'completed':0,'unstarted_closed':11,'closed':True,'remaining':0},'V80':{'completed':12,'pairs':6,'closed':True,'remaining':0}},'total_completed_distinct_approved_scopes':217,'new_paid_calls':0,'historical_paid_spend_usd':'0.071799','target_execution':False,'new_profiles':0,'new_comparators':0,'no_old_budget_reopened':True}
p['declining_acceptance']='If the user requests detection-support changes rather than accepting this exact limitation scope, retain the first-frozen failure and continue approved-contract source work; any newly required source/contract/performance decision and exact numerical regression approval remain separate. Do not automatically start another fresh batch.'
with (OUT/'acceptance-proposal.json').open('x') as f:json.dump(p,f,indent=2);f.write('\n')
url='https://github.com/BashaarJavaid/MCP-Sentinel/blob/phase22/integration/artifacts/phase22/integration/'
body=f'''The requested unseen check is complete at frozen `cec0322`: **12 complete observations, six equal ordered pairs; Taskwarrior passes its narrow shell condition, Proxmox fails vulnerable-read detection and fixed/safe support.** Proxmox's computed module-table dispatcher remains unsupported. All4findings/504diagnostics/12surfaces/18contexts and14ordered comparisons are source-assessed. No tuning, target execution or paid calls.

The initial V78 metadata failure remains one incomplete before analysis, zero reports and eleven unstarted closed. Both budgets are closed. Existing V73/V75 retain205completed exposed observations/95pairs; actual unchanged engineering remains2,450tests/36skips locally and all12hosted suites,29normal jobs/docs, plus affected final docs/packages.

[Review summary]({url}v81-technical-acceptance/summary.md) · [448-row audit]({url}v81-technical-acceptance/audit.json) · [All proposed limitations]({url}v81-technical-acceptance/acceptance-limits.md) · [Explicit technical acceptance proposal]({url}v81-technical-acceptance/acceptance-proposal.json), SHA-256 `{sha(OUT/'acceptance-proposal.json')}`.

**26 limitation rows are proposed, not accepted**, including the new Proxmox failure, initial metadata failure, all earlier fresh/native/profile/equivalence failures, ordinary1,800-second FAF completion remaining unestablished, and leavingV68unopened. Git312/1,040incomplete/728deferred; paid benchmark/pilots deferred; Phase21incomplete,Phase24/15unchanged. No broad accuracy, speedup or runtime-safety claim.

**Phase22remains incomplete until separate explicit human technical acceptance and verified accepted-closeout delivery.** No merge, ready-state change, release, outreach or Phase23 is authorized.
'''
for a,b in [('All4','All 4'),('and14','and 14'),('retain205','retain 205'),('observations/95pairs','observations / 95 pairs'),('remains2,450tests/36skips','remains 2,450 tests / 36 skips'),('all12hosted','all 12 hosted'),('suites,29normal','suites, 29 normal'),('ordinary1,800','ordinary 1,800'),('leavingV68unopened','leaving V68 unopened'),('Git312/1,040incomplete/728deferred','Git 312/1,040 incomplete, 728 deferred'),('Phase21incomplete,Phase24/15unchanged','Phase 21 incomplete, Phase 24/15 unchanged'),('Phase22remains','Phase 22 remains'),('Phase23','Phase 23')]:body=body.replace(a,b)
with (OUT/'pr-body.md').open('x') as f:f.write(body)
print('Explicit unaccepted technical proposal',sha(OUT/'acceptance-proposal.json'),'448requirements/26limitation rows; Proxmox failure retained.')
