"""Generate or check the locked runtime dependency license inventory."""

from __future__ import annotations

import argparse
import importlib.metadata
from collections import deque
from email.message import Message
from pathlib import Path
from typing import cast

from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "THIRD_PARTY_NOTICES.md"
LICENSE_OVERRIDES = {
    "face": "BSD-3-Clause",
    "glom": "BSD-3-Clause",
    "peewee": "MIT",
    "tiktoken": "MIT",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rendered = render_notices()
    if args.check:
        current = (
            args.output.read_text(encoding="utf-8") if args.output.is_file() else None
        )
        if current != rendered:
            print(f"third-party notices drifted: {args.output}")
            return 1
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    return 0


def render_notices() -> str:
    rows = []
    for distribution in runtime_distributions():
        metadata = distribution.metadata
        name = _metadata_value(metadata, "Name") or "unknown"
        version = distribution.version
        license_name = _license_name(metadata)
        source = _source_url(metadata)
        license_files = sorted(
            str(item)
            for item in distribution.files or ()
            if "license" in str(item).lower() or "copying" in str(item).lower()
        )
        files = ", ".join(license_files) if license_files else "metadata only"
        rows.append((name, version, license_name, source, files))
    lines = [
        "# Third-party notices",
        "",
        "Generated by `python scripts/generate_third_party_notices.py` from the",
        "installed, locked runtime dependency closure. Run the command again after",
        "dependency changes and review every license before release.",
        "",
        "| Package | Version | License | Source | Packaged notice files |",
        "|---|---:|---|---|---|",
    ]
    for name, version, license_name, source, files in rows:
        lines.append(
            f"| {_cell(name)} | {_cell(version)} | {_cell(license_name)} | "
            f"{_cell(source)} | {_cell(files)} |"
        )
    lines.extend(
        (
            "",
            "MCP Sentinel remains licensed under the repository `LICENSE`. This file",
            "does not replace dependency license texts; those files remain",
            "authoritative for their respective packages.",
            "",
        )
    )
    return "\n".join(lines)


def runtime_distributions() -> tuple[importlib.metadata.Distribution, ...]:
    project = importlib.metadata.distribution("mcp-sentinel")
    pending = deque(_requirements(project))
    seen: set[str] = set()
    found: dict[str, importlib.metadata.Distribution] = {}
    while pending:
        requirement = pending.popleft()
        normalized = _normalize(requirement.name)
        if normalized in seen or not _applies(requirement):
            continue
        seen.add(normalized)
        try:
            distribution = importlib.metadata.distribution(requirement.name)
        except importlib.metadata.PackageNotFoundError as error:
            raise RuntimeError(
                f"locked runtime dependency is not installed: {requirement.name}"
            ) from error
        found[normalized] = distribution
        pending.extend(_requirements(distribution))
    return tuple(found[name] for name in sorted(found))


def _requirements(
    distribution: importlib.metadata.Distribution,
) -> tuple[Requirement, ...]:
    return tuple(Requirement(item) for item in distribution.requires or ())


def _applies(requirement: Requirement) -> bool:
    if requirement.marker is None:
        return True
    return requirement.marker.evaluate({"extra": ""})


def _license_name(metadata: importlib.metadata.PackageMetadata) -> str:
    normalized = _normalize(_metadata_value(metadata, "Name"))
    if normalized in LICENSE_OVERRIDES:
        return LICENSE_OVERRIDES[normalized]
    expression = _metadata_value(metadata, "License-Expression")
    if expression:
        return expression.strip()
    value = _metadata_value(metadata, "License").strip()
    if value and len(value) <= 120 and "\n" not in value:
        return value
    classifiers = metadata.get_all("Classifier") or []
    licenses = [item.split(" :: ")[-1] for item in classifiers if "License ::" in item]
    return ", ".join(licenses) if licenses else "REVIEW REQUIRED"


def _source_url(metadata: importlib.metadata.PackageMetadata) -> str:
    for raw_item in metadata.get_all("Project-URL") or []:
        item = str(raw_item)
        label, separator, value = item.partition(",")
        if separator and label.strip().lower() in {
            "source",
            "repository",
            "homepage",
            "code",
        }:
            return value.strip()
    return (_metadata_value(metadata, "Home-page") or "not declared").strip()


def _metadata_value(metadata: importlib.metadata.PackageMetadata, name: str) -> str:
    value = cast(Message, metadata).get(name)
    return str(value) if value is not None else ""


def _normalize(value: str) -> str:
    return value.lower().replace("-", "_").replace(".", "_")


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
