"""Preserve the invalid interrupted profile and prepare a corrected, unexecuted one."""
import ast,copy,hashlib,json,subprocess
from datetime import datetime,timezone
from pathlib import Path
OUT=Path(__file__).resolve().parent;BASE=OUT.parent;ROOT=OUT.parents[3];OLD=BASE/'v49-allocation-regression'
read=lambda p:json.loads(p.read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def write(name,value):
    with (OUT/name).open('x') as f:json.dump(value,f,indent=2);f.write('\n')
p=read(OLD/'diagnostic-proposal.json');a=read(OLD/'diagnostic-authorization.json');attempt=read(OUT/'attempt.json');result=read(OUT/'measurement/results.json')
assert a['approved'] and a['proposal_sha256']==attempt['proposal_sha256']==sha(OLD/'diagnostic-proposal.json')
assert attempt['approval_sha256']==sha(OLD/'diagnostic-authorization.json')
assert attempt['scanner']==result['scanner']==p['scanner']
assert result['manifest_sha256']==p['manifest_sha256']
assert result['authorization_sha256']==sha(Path(p['frozen_checkout'])/p['source_freeze_approval'])
assert result['model_calls']==0 and not result['requests']
assert len(result['outcomes'])==1 and result['outcomes'][0]['state']=='incomplete'
assert result['outcomes'][0]['configuration_sha256']==p['input']['configuration_sha256']
assert read(OUT/'budget-closed.json')['budget_closed'] and read(OUT/'budget-closed.json')['remaining']==0
assert not (OUT/'execution.json').exists() and not list(OUT.glob('SENT-*-cpu-samples.json'))
assert not list((OUT/'measurement').glob('*/report.*'))
assert read(OUT/'owned-work.json')['owned_processes']==[]
original=OUT/'sampling-worker.py';assert sha(original)==sha(OLD/'sampling-worker.py')
assert "root=Path('/private/tmp/mcp-phase22-frozen-17b4784')" in original.read_text()
source=ROOT/'src/sentinel/static/workers.py';assert 'str(WORKER)' in source.read_text() and 'cwd=WORKER.parent' in source.read_text()
assessment={'recorded_at':datetime.now(timezone.utc).isoformat(),'scanner_expected':p['scanner'],'parent_scanner_reported':result['scanner'],'validation_passed':True,'profile_gate_passed':False,'status':'invalid interrupted profile: stale worker import root','profile_attempts':1,'completed_inputs':0,'incomplete_inputs':1,'valid_current_source_profiles':0,'report_count':0,'sample_snapshots':0,'finding_count':None,'warning_count':None,'surface_count':None,'source_assessment_complete_for_retained_outputs':True,'harness_outcome':result['outcomes'][0],'whole_input_seconds':None,'cleanup_seconds':None,'cleanup_verified_by_post_stop_process_inventory':True,'budget_closed':True,'remaining':0,'manual_stop':{'signal':'SIGTERM','owned_supervisor_pid':82270,'tool_exit_code':1,'tool_stdout':'supervisor termination','reason':'Source inspection found the sealed sampler literal points to old frozen17b4784 while approved parent/proposal specifies6e4fd67. Supervisor was stopped immediately; its finally reaped owned children. Diagnostic finally closed its budget. Its post-supervise execution.json writer was bypassed by SystemExit, so no exact supervisor timing is claimed.'},'source_explanation':'The sampler prep reused the old file byte-for-byte and failed to replace its literal sys.path root. Parent scanner_identity and proposal file hashes did not prove subprocess import identity. The synthetic sampler test checked values and timer restoration but lacked an expected worker-source assertion. No worker snapshot or startup identity receipt exists, so actual worker progress is unknown. The interrupted result is invalid for current-source attribution, not a timing miss, condition result, or fresh pass. This is an agent preparation error, not an observed scanner product defect.','worker_import_root_in_sealed_source':'/private/tmp/mcp-phase22-frozen-17b4784','worker_scanner_observed':None,'proposal_sha256':sha(OLD/'diagnostic-proposal.json'),'approval_sha256':sha(OLD/'diagnostic-authorization.json'),'source_bindings':{str(f.relative_to(ROOT)):sha(f) for f in [original,OLD/'diagnostic.py',OLD/'sampler-selfcheck.py',ROOT/'src/sentinel/static/workers.py',ROOT/'scripts/phase20_measurements.py',BASE/'v20-linux-diagnostic-v1/runner.py']},'retained_raw_sha256':{str(f.relative_to(OUT)):sha(f) for f in [OUT/'attempt.json',OUT/'budget-closed.json',OUT/'measurement/results.json',OUT/'measurement/faf-read-root-vulnerable/configuration.json',OUT/'observation.log',original]},'prior_native205_budget_unchanged':True,'prior_native_attempts':1,'prior_native_unstarted_closed':204,'optimization_attempts':0,'uninstrumented_observations':0,'retries':0,'paid_calls':0,'target_execution':False,'technical_acceptance_received':False,'phase22_complete':False}
write('assessment.json',assessment)
check=read(OUT/'sampler-selfcheck/packet.json');assert check['wrong_root_rejected_before_execution'] and check['worker_identity']['scanner']==p['scanner']
assert check['original_scanner_methods_identical'] and check['same_value_results'] and check['prior_signal_and_timer_restored']
assert not subprocess.check_output(['git','diff','6e4fd67','--','src','tests','scripts','schemas','.github','uv.lock','pyproject.toml'])
write('source-correction.json',{'scope':'Diagnostic wrapper only; scanner product unchanged','old_sampler_sha256':sha(original),'corrected_sampler_sha256':sha(OUT/'corrected-sampling-worker.py'),'corrections':['Use the exact approved frozen6e4fd67 import root.','Verify actual worker/flow module paths and full source/harness/revision identity before timer setup and target snapshot deserialization.','Parent preflight runs isolated worker check and checks its identity before one-use token creation.','Each real worker would retain a startup identity receipt before sampling.'],'synthetic_check_sha256':sha(OUT/'sampler-selfcheck/packet.json'),'negative_control':'A copy pointing at old17b4784 fails identity verification before any timer or target snapshot access.','product_source_unchanged':True,'new_corpus_executions':0,'paid_calls':0})
proposal=copy.deepcopy(p)
proposal.update(status='prepared_not_approved_not_executed',purpose='Correct the agent-authored stale sampler import root and obtain the originally intended current-source FAF profile. The invalid interrupted attempt remains preserved and closed. This is one new separately approved attempt, not a reopened budget.',command=['/Users/bashaarjavaid/Projects/MCP-Sentinel/.venv/bin/python','-I',str(OUT/'diagnostic.py')],output=str(BASE/'v51-faf-bound-sampling'))
proposal['instrumentation']='Same100Hz stdlib CPU-timer worker sampler, rule set, process layout and300-second limit. Correct import root to6e4fd67 and verify actual worker/flow paths plus complete scanner source/harness/revision before sampling or reading a target snapshot. Parent preflight executes an isolated check before consumption. Real workers retain startup identity receipts. Identity-check overhead remains inside the same whole-input limit; methods and target source are unchanged. No locals/source values are recorded.'
proposal['interpretation']+=' The interrupted v50 attempt has no profile or report and cannot be used as a current-source baseline. Per-worker receipts must all bind6e4fd67; missing/mismatched receipts invalidate attribution. Existing v47 samples remain17b4784-only.'
proposal['stop']='At most one attempted input including incomplete/interruption/identity failure. Stop before execution on preflight mismatch, and close the attempt on worker identity, timeout, execution or cleanup failure. Preserve partial outputs. No automatic retry, optimization, resource/deadline change or reopening either closed205-observation or invalid-profile budget.'
files=[OLD/'diagnostic-proposal.json',OLD/'diagnostic-authorization.json',OLD/'diagnostic-consumed.json',BASE/'v48-merge-allocation/evaluate.py',OUT/'corrected-sampling-worker.py',OUT/'diagnostic.py',OUT/'sampler-selfcheck.py',OUT/'sampler-selfcheck/packet.json',OUT/'source-correction.json',OUT/'assessment.json',OUT/'budget-closed.json',BASE/'v43-four-fresh-preparation/runner.py',BASE/'v20-linux-diagnostic-v1/runner.py']
proposal['files_sha256']={str(f.relative_to(ROOT)):sha(f) for f in files}
write('diagnostic-proposal.json',proposal)
print('Invalid interrupted attempt preserved; zero reports/snapshots; corrected worker identity and rejection checks pass. New single-profile proposal remains unapproved.')
