"""Render the actual failure and exact unapproved next decision."""
import hashlib,json,re,shutil
from pathlib import Path
out=Path(__file__).resolve().parent;base=out.parent;root=out.parents[3];assets=base/'v62-shared-tool-discovery';read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
a=read(out/'assessment.json');p=read(out/'diagnostic-proposal.json')
initial=(out/'status.md').read_text();status='\n'.join(re.sub(' {2,}',' ',line).rstrip() for line in initial.split('\n')).replace('89 original+263 added','89 original + 263 added')
(out/'initial-status.md').write_text(initial);shutil.copyfile(out/'owning-docs.json',out/'initial-owning-docs.json')
docs=list(read(out/'owning-docs.json')['sha256'])
for n in docs:
 f=root/n;s=f.read_text();assert s.count(initial)==1,n;f.write_text(s.replace(initial,status,1))
(out/'status.md').write_text(status);(out/'owning-docs.json').write_text(json.dumps({'sha256':{n:sha(root/n) for n in docs}},indent=2)+'\n')
summary=f'''# Shared-discovery regression timed out; parent-and-worker diagnostic proposed

**The approved 205-observation regression at `1948bf9` stopped on the first FAF vulnerable input after {a['whole_seconds']:.9f} seconds. One incomplete input, no reports, 204 unstarted observations closed, zero remaining. Phase 22 remains incomplete.**

The exact `approved` decision binds [authorization](../v62-shared-tool-discovery/evaluation-authorization.json) to proposal `c1407c3a8cb7ee78ebf4346ab1e36e112dcb1e830e4c8270c563d780f2861a9b`, delivered at `c7b20a3`. [Preflight](../v62-shared-tool-discovery/execution-preflight.json) verified the frozen scanner, intended imports, protected state and absence of conflicting owned work before the one-use launch. Scanner `{a['scanner']['revision']}`; source SHA-256 `{a['scanner']['source_sha256']}`; harness `{a['scanner']['harness_sha256']}`. The lock, original FAF source/configuration/condition, rules-only treatment and entire ordered schedule matched approval.

## Actual outcome and source assessment

[Validation](validation.json) and [assessment](assessment.json) retain **{a['whole_seconds']:.9f} seconds** whole-input time and **{a['whole_including_cleanup_seconds']:.9f} seconds** including cleanup. Cleanup used about {a['whole_including_cleanup_seconds']-a['whole_seconds']:.3f} seconds of its separate 15-second allowance; no remaining-group kill was needed. The outer sequence took {a['sequence_seconds']:.9f} seconds and did not itself time out. The measurement harness retained an incomplete result at {a['harness_wall_duration_ms']:,} ms, with null reason, no requests and zero model calls. The child log says `supervisor termination`; the evaluator then failed its completion assertion. The supervisor's SystemExit bypasses the harness's `except Exception`, while its finally writer preserves the incomplete outcome. These are distinct retained receipts, not conflicting time measurements.

**No native JSON/SARIF report exists. Finding, warning and surface counts are unknown, not zero.** Named vulnerable detection, fixed/control support and ordered-repeat equality are unmeasured. All remaining 23 four-repository and 181 earlier-language observations are unstarted and closed. The input's source, original label, fixed/control prerequisites and complete old reports remain unchanged. `inventory.py` is prepared but unused because there is no report to inventory; it is not measured zero-diagnostic evidence.

No stack or stage trace identifies the residual cost. The source establishes that `run_flow_rules` now requests completed TypeScript discovery in the parent before dispatching its existing workers, then shares that result through IPC and parent coverage. The previous v61 worker-only profile belongs to `7bf4c6e`, before this movement. It cannot establish current parent or worker costs, and another worker-only profile could omit work now occurring before dispatch. Retained child resource counters include descendant work; their totals do not identify stages, prove worker launch history or measure native speedup. **The reuse candidate has not established 1800-second completion or a native speedup.**

[Owned-work verification](owned-work.json) confirms no remaining owned process or Sentinel container after the stopped execution. No retry, profile, comparator, target execution, new repository, resource/timeout change or paid call occurred. The [budget receipt](budget-closed.json) closes the exact sequence; no old approval is reusable.

## Exact next diagnostic, unapproved and unexecuted

[Diagnostic proposal](diagnostic-proposal.json), SHA-256 `{sha(out/'diagnostic-proposal.json')}`, requests **one sampled FAF vulnerable input** at the same frozen `1948bf9`, with **1800 seconds whole-input maximum and 15 seconds cleanup**. No optimization attempt or uninstrumented retry is included. The 120-second target stays informational.

The proposal reuses the same five sampling functions—`sample`, `snapshot`, `snapshots`, `start`, `finish`—with AST-identical implementations, 100 Hz CPU timers, a 1024-frame cap and atomic 15-second snapshots. It adds sampling around the existing parent `measure()` call and retains the existing worker entry wrappers: **one parent plus at most four existing flow workers**, not additional scanner workers. Parent and sampled worker identities include actual worker, TypeScript flow and discovery import paths and full source/harness identities. Identity checks precede target source validation and timer/worker snapshot access. Scanner methods, rules, dependency versions, resources and shared timeout remain unchanged.

The attempted-input timer starts before child imports/preflight and includes configuration, materialization, analysis, reports and sampling overhead. Cleanup is separately limited to 15 seconds. Read-only launcher provenance preflight occurs before consumption and performs no scan. The initial proposal wording was clarified to make that distinction precise; [initial preparation](initial-diagnostic-proposal.json) and the exact clarification helper/receipt remain preserved. No execution or timing policy changed.

[Worker sampler controls](sampler-selfcheck/packet.json) preserve six synthetic combination vectors and scanner methods, validate sample/frame references and restore prior signal/timer state. A stale `7bf4c6e` worker root rejects before sampling or target execution. [Parent wrapper controls](parent-sampler-selfcheck/packet.json) exercise the actual wrapper with synthetic completed and interrupted work, verify source identity, positive samples, timer restoration and worker-entry restoration, and reject a stale parent before input access. [Missing-approval validation](../v63-diagnostic-boundary.json) rejects before creating the diagnostic output or consumed token. All controls are scanner-owned synthetic work; zero corpus executions occurred in preparation.

Sampling is statistical. Native-code/GIL signal delivery, snapshot threads and serialization can bias attribution. The parent gets one diagnostic snapshot thread in addition to the existing per-worker sampler threads; all overhead is disclosed and included in attempted-input accounting. Parent and worker percentages have separate denominators and overlapping inclusive stacks; they are not additive savings. Parent sampling surrounds `measure()` and does not include earlier launcher/source preflight CPU. In `parent-cpu-samples.json`, legacy `worker_cpu_seconds` and `final_worker_snapshot` field names describe that parent process.

Every attributed process requires its matching identity. Missing or mismatched identities invalidate that attribution and remain explicit failures. Worker snapshots may be absent if discovery has not reached dispatch, but absence alone does not prove that workers never started. Parent-only evidence cannot establish worker costs or completeness. Retain periodic and incomplete temporary outputs if mandatory cleanup prevents a final/restored snapshot; never extend cleanup to improve evidence. If a report completes, validate JSON/SARIF and compare the entire ordered report to the original `2e0efb2` reference using only the established 11 volatile exclusions, then assess every change. This one profile will not itself establish a native regression pass.

**No retries, comparators, paid calls, target execution, new repositories, optimization, resource change or deadline revision are authorized by the pending proposal.** The one-use diagnostic must stop and close its budget on every attempted outcome. It remains unapproved and unexecuted; no `v64-shared-discovery-sampling` directory or diagnostic token exists.

## Engineering, history and acceptance

[Compatible reuse](compatible-reuse.json) verifies all 302 engineering inputs against frozen `1948bf9`: **2,418 passed / 36 skipped** locally and in all **12 hosted suites**, all **29 normal CI jobs** and docs passed in [34793663094](https://github.com/BashaarJavaid/MCP-Sentinel/actions/runs/34793663094) / [34793663105](https://github.com/BashaarJavaid/MCP-Sentinel/actions/runs/34793663105). Actual hosted merge/tree `a93b425c925cd2dcaa57371597656767a32ede34` matches the candidate. Combined statement/branch coverage is **90.08%**, branch-only **85.92%**. Six complete zero-call production request replays and 19 approved runtime component/image bindings remain compatible. This continuation adds retained-result, diagnostic preparation and final docs/package checks; it is not another hosted code run or production capture. Original synthetic discovery equivalence and one-producer accounting remain engineering evidence, not native completion.

[The audit](audit.json) preserves **all 345 prior requirements** and adds seven: **352 total, 89 original + 263 added**. V62 delivery and evaluation decision change only with their actual receipts and complete previous rows retained. Original rows remain 84 passed, two user-deferred, two proposed limitations and one unresolved human acceptance. Before supplemental delivery, added rows have 240 passed, six proposed historical closures and 17 unresolved. Every prior requirement keeps its source-bound evidence and a current execution interpretation. No failed gate or limitation is accepted by the agent.

All six native timeouts remain at their actual sources: `17b4784`, `6e4fd67`, `a36f696`, `dc73715`, `7bf4c6e` and now `1948bf9`, each one incomplete plus 204 closed unstarted observations. The four valid partial profiles retain 86,659 / 79,307 / 78,769 / 432,756 samples at their earlier sources. The invalid stale-worker attempt and unresolved V49-DIAGNOSTIC-PREPARATION remain; neither singleton equivalence failure is erased by the later approved credential correction. Six historical closure proposals remain unaccepted.

The original four-repository fresh result remains **24 completed observations, 12 equal pairs, all four repository gates failed at `2e0efb2`**: FAF, Lightning Python and Engram missed named vulnerable sinks; no-bash falsely alerted on fixed/control inputs. Quiet unsupported paths do not pass. Earlier TS94/47 pairs at `2e0efb2`, Python87/36 pairs at `8c62567`, and whole25 development reuse plus45+45 Linux at `1f3f72f` retain actual bindings and the Meta operator erratum. Language subsets never become a new whole batch. Original memory-keeper false alerts, DDG unsupported fixed send and incorrect TypeScript metadata despite Python execution, Lighthouse misses and held-out10 complete/10 unsupported/5 incomplete with zero hits among four completed vulnerable inputs out of ten vulnerable total remain visible.

Git remains **312/1,040 incomplete**, 728 deferred; paid benchmark/pilots deferred, Phase21 incomplete and Phase24/15 unchanged. Historical two paid calls remain **$0.071799 total**; this continuation adds zero. Same-agent review is not independent human validation, broad accuracy, training-data novelty or runtime safety proof. **Phase22 remains incomplete**, pending actual current-source gates or an explicit applicable user disposition, then separate human technical acceptance and verified accepted closeout. No merge, ready-state, release, outreach or Phase23 is authorized.
'''
(out/'summary.md').write_text(summary)
url='https://github.com/BashaarJavaid/MCP-Sentinel/blob/phase22/integration/artifacts/phase22/integration/v63-shared-discovery-regression/'
body=f'''The approved regression at `1948bf9` still times out on its first FAF input after {a['whole_seconds']:.3f} seconds. No report exists; cleanup passed and all204unstarted observations are closed. Detection and compatibility remain unestablished.

[Review packet]({url}summary.md) · [352-row audit]({url}audit.json) · [exact diagnostic proposal]({url}diagnostic-proposal.json)

The next proposal is unapproved and unexecuted: one sampled FAF input,1800-second maximum plus15-second cleanup,using the existing CPU-timer sampler in the parent and any of the four existing workers. Discovery now runs in the parent before dispatch,so old worker-only samples cannot establish current costs. Source-identity,stale-root,parent completion/interruption,timer and missing-approval controls pass. No optimization,retry,comparator,target execution,resource/deadline change or paid call.

Product retains verified `1948bf9`:2,418tests/36skips locally and all12hosted suites,29normal CI jobs and docs passed. Six complete production requests retain zero-call replay evidence. All earlier failures remain preserved; no native speedup is established.

Phase22 remains incomplete pending current-source gates,explicit human technical acceptance and accepted closeout. Git312/1040 incomplete; paid benchmark/pilots deferred,Phase21 incomplete,Phase24/15 unchanged. No merge,ready-state,release,outreach or Phase23.
'''
(out/'pr-body.md').write_text(body)
print('Rendered stopped outcome,352-row audit and exact unapproved parent-and-worker diagnostic.')
