"""Render the actual tested correction and exact unapproved follow-up scope."""
import json
from pathlib import Path
out=Path(__file__).resolve().parent;read=lambda p:json.loads(p.read_text())
local=read(out/'local-checks.json');p=read(out/'evaluation-proposal.json');audit=read(out/'audit.json');binding=read(out/'launcher-binding.json')
assert len(audit['requirements'])+len(audit['additional_scope_requirements'])==407
assert local['candidate']==p['scanner']['revision'] and not (out/'evaluation-authorization.json').exists()
cov=local['coverage_totals'];head=local['candidate'];url='https://github.com/BashaarJavaid/MCP-Sentinel/blob/phase22/integration/artifacts/phase22/integration/v72-prototype-property-correction/'
s=f'''# Correctness recovery verified; actual regression approval pending

**Candidate `{head}` passes 2,450 tests / 36 skips locally and in all 12 hosted suites. All 29 normal CI jobs and docs pass. Its actual corpus behavior remains unmeasured. Phase 22 remains incomplete.**

## What changed and why

The completed [V70 uncapped experiment](../v70-uncapped-four-results/summary.md) supplied 24 complete reports and 12 equal entire ordered pairs at `4145d35`. No-bash and Engram passed their frozen narrow conditions. FAF missed its named read and left negatives unsupported; Lightning detected its vulnerable request but failed the required fixed/safe initial-literal qualifier. All 260 findings, 52,492 diagnostics, 282 surfaces, 4,963 contexts and complete reference differences remain source-assessed. FAF took 2,212.22–2,341.48 seconds per input; non-FAF inputs took 6.28–10.72 seconds. These measured older-source timings neither predict the corrected candidate nor establish success under the normal 1,800-second policy. V70 is closed with zero remaining budget.

The user-requested protected continuation prompt §2 authorizes ordinary approved-contract correctness work. The [intake](intake.json) and original v45 authorization require actual caller/value/sink support and narrow initial-literal guard recognition. These changes continue that existing recovery contract; they do not implement the separately unapproved V68 performance proposal or waive any failed gate.

The shared TypeScript interpreter previously rejected ordinary constructor parameter properties. It now binds all arguments/defaults before assigning the final parameter values to the actual instance markers and executing the constructor body. Existing unsupported inheritance, decorators, replacement and escape checks remain. Duplicate/colliding properties, initialized instance fields with unestablished emit order and `__proto__` prototype mutation remain unsupported. The [source assessment](source-assessment.json) binds actual source and tests; the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties) defines the supported visibility/readonly property syntax. No compiler or target code was executed.

Python URL analysis now retains initial guard evidence through exact trailing-slash removal and known path suffixes only when the checked destination remains established. Exact parsed hostname identity is separated from fallback-combined values; component-returning helpers retain that identity. Derived URLs receive distinct keys, and trimming removes authority evidence that a later suffix could invalidate. Wrong/reassigned values, caught exceptions, hostname fallback, arbitrary trim arguments, formatting and authority substitution remain conservative. The resulting broad candidate keeps only the existing initial-private-literal IPv4 qualifier, with DNS/redirect/rebinding uncertainty explicit.

These are source-established correctness fixes, not proof that either real repository now passes or becomes faster. All rule-specific analysis and the approved private invalidation contract remain; no new discovery language/origin, target execution, worker/resource change or normal deadline revision is included.

## First failures and corrections

- Initial baseline synthetics: five failures / 89 passes, reproducing two constructor and three URL-qualification misses. The targeted subset also failed the inherited global coverage gate at 31.26%; later focused checks use `--no-cov`, while full engineering keeps configured coverage and separately requires branch-only coverage >=80%.
- First correction: one existing normalization/pinning regression / 93 passes. Returning a hostname was incorrectly wrapped as a Boolean predicate. The shared component-key correction restores the CGNAT qualifier; 96 then 104 cases passed with extra fallback, authority, formatting, defaults, instance and decorator controls.
- Discovery/worker checks: 119 passed; a further explicit nonempty-discovery assertion passed for both cold/warm parameter-property cases. Ordered complete rule state, pickle node identity and serial/parallel execution were compared.
- A later independent `__proto__` control failed at first candidate `42d6c7c`. Direct parameter-property assignment bypassed the existing prototype-assignment rejection. Its local suite was deliberately interrupted after 1,408 passes / 36 skips in 682.16 seconds, exit 2; CI 34845266890 was cancelled, docs 34845266900 passed. Those partial artifacts remain retained and are not a complete engineering pass. No JSON coverage report was emitted on interruption.
- Corrected `cec0322` adds precisely the special-property rejection: removing that one AST guard recovers the complete previous product AST. All 224 focused cases pass. Full engineering below binds this final source.
- The first V72 source-assessment helper failed when it expected the interrupted run's nonexistent coverage JSON. Its exact helper and failure remain; the corrected assessment records the absence rather than inventing coverage. Earlier read-only missing-path checks and the case-sensitive process-identity filter failure sent no signal or mutation; the exact owned pytest PID was verified before interruption.

## Actual engineering and compatibility

[Local checks](local-checks.json) retain **2,450 passed / 36 skipped**, with combined statement/branch coverage **{cov['percent_covered']:.6f}%** and actual branch-only **{cov['percent_branches_covered']:.6f}%**. Ruff, format, whole-scope strict mypy, unchanged lock, native schema/SARIF, dependency advisories/notices, offline generated artifacts, strict docs, wheel/sdist and installed-runtime requirements pass.

[Hosted engineering](../v72-candidate-quality-audit/packet.json) binds all 12 Linux/macOS/Windows × Python 3.10–3.13 suites, all 29 normal jobs and docs in **34846514312 / 34846514328**, including installed wheels, Docker replay, network isolation, Action/hooks and ordinary historical reproduction. [Actual checkout](checkout-binding.json) is merge `b19c68cae75c8804ede7fb885db96b5efd1292aa`, tree `097c119cd27f75596ba11f434089610fb7907599`, exactly equal to the candidate tree with the preserved PR36 parent. All four optional current-corpus jobs remain skipped. Normal CI's historical reproduction remains pinned to `8824014`, not this current candidate.

All 303 engineering inputs bind to final source; seven differ from the last complete `4145d35` baseline across source, tests and changelog. [Six complete production requests](../v72-production-capture-revalidation/packet.json) regenerate and checked-replay unchanged, with live transport forbidden and zero paid calls. [Runtime compatibility](compatibility.json) preserves all 19 components and approved Git image. The owned demo's 20/20 attempts and 14 findings remain a narrower engineering result, not completion of deferred Git campaigns. Final README-aware packages are rebuilt and compared with actual hosted product/schema/fixture bytes separately.

## Exact proposed next run — unapproved

[Proposal](evaluation-proposal.json), SHA-256 **`{binding['proposal_sha256']}`**, is one new serial local **24-observation** exposed regression: **12 input records twice / 12 entire ordered pairs**. Preserve four repositories first: 18 non-FAF observations in existing first/repeat order, then six FAF. Original source archives, configurations, caller/guard/sink prerequisites, labels and all failed gates remain. [Rubric](scoring-rubric.json) requires named vulnerable detection plus supported fixed/safe discrimination; quiet unsupported negatives fail. Compare all ordered report fields with only the established 11 volatile names excluded; assess every finding, warning, unresolved flow, surface and difference against original and immediately preceding reports.

Scanner source SHA-256 **`{p['scanner']['source_sha256']}`**, harness **`{p['scanner']['harness_sha256']}`**, lock **`{p['lock_sha256']}`**; [frozen checkout](freeze.json) **`{p['frozen_checkout']}`**. This preparation happens only after full engineering. No current-source input has run, no approval/token exists, and zero measurement budget is open.

The proposal uses the same verified **experiment-only uncapped** policy: no input/sequence time cap and Semgrep rule timeout 0, one input at a time with existing workers; **15-second finite cleanup** retained. The normal shared 1,800-second deadline remains unchanged. Ten complete Python/TypeScript/mixed/parameter-property serial/parallel [policy comparisons](synthetic-equivalence.json), [restoration/cancellation checks](boundary-checks.json) and the missing-approval boundary pass. User cancellation or identity/execution/schema/cleanup/ordered-repeat failure stops and closes all unused observations. Named detection failure alone does not stop collection. No retry, profile, comparator, new repository, target execution, source tuning, paid call or resource upgrade is included. Historical 37–39-minute FAF times are not a new duration estimate or guarantee.

The **181 earlier Python/TypeScript observations remain outside this proposal** and require later exact approval; their current-source compatibility gates remain unresolved. Neither this proposal nor a later regression approval is technical acceptance.

## Preserved obligations and closeout state

The [407-row audit](audit.json) retains all **399 prior rows**, including the prior V70 delivery row and explicit V68 status correction, plus the actual first prototype failure/interrupted engineering and six current correction/preparation requirements. Original dispositions remain 84 passed, two user-deferred, two proposed limitations and unresolved human acceptance. Added dispositions before final supplemental delivery are 290 passed, six unaccepted historical closures and 22 unresolved. Actual draft delivery resolves only its own row.

All seven native timeouts, six valid partial profiles, invalid stale-root profile/preparation, both singleton failures and strict invalidation failure retain actual source bindings. Original four-repository fresh gates remain all failed at `2e0efb2`; the two newer narrow passes are exposed outcomes at `4145d35`. Historical TS94/47 pairs, Python87/36 pairs, whole25 development reuse and whole45+45 Linux remain source-bound with DDG/Meta errata and no pooled subset claim. Original held-out results remain 10 complete / 10 unsupported / five incomplete, zero hits among four completed vulnerable inputs out of ten vulnerable total. Six historical closure proposals remain unaccepted: V14-RETENTION, V21-SEQUENCE, V21-FRESH-PROPOSAL, V25-EXPOSED-REGRESSION, V27-REGRESSION and V39-EVALUATION. Same-agent source review is not independent validation, broad accuracy or runtime proof.

The V68 literal-serialization optimization remains **unapproved/unimplemented**, proposal SHA `fa4ffc3760d4b85b4f8236eec5c7b28d979ece894515bb1495046dd1db108cf6`. No historical measurement budget is reused. Nine protected user documents, earlier worktrees/seals, file restoration and selective Docker cleanup evidence remain preserved; no new cleanup/resource change occurred and the disappearance cause remains unknown.

Git stays **312/1,040 incomplete with 728 deferred**; the 396-request paid benchmark and external pilots remain user-deferred. Historical paid total stays **$0.071799**, zero added. Phase 21 remains incomplete; Phase 24/15 unchanged. **Phase 22 is incomplete pending actual current-source gates, explicit human technical acceptance and subsequent verified accepted closeout.** No merge, ready-state change, release, outreach or Phase 23.
'''
with (out/'summary.md').open('x') as f:f.write(s)
body=f'''Candidate `{head}` corrects ordinary TypeScript constructor parameter-property support and preserves narrow Python initial URL guard qualification across proved trimming/path derivation. A separately caught `__proto__` boundary failure is fixed; initial failed synthetics, interrupted local suite and cancelled CI remain retained.

[Review]({url}summary.md) · [407-row audit]({url}audit.json) · [Exact unapproved24-observation proposal]({url}evaluation-proposal.json)

Actual final-source engineering passes2,450 tests/36 skips locally and in all12hosted suites, all29normal jobs and docs. Combined coverage{cov['percent_covered']:.2f}%, branch-only{cov['percent_branches_covered']:.2f}%. Exact checkout/package bindings, six identical zero-call production requests and19runtime components pass. All407requirements and original source-bound failures remain.

The previous4145d35 uncapped run remains24complete/12equal pairs, with no-bash/Engram narrow passes and FAF/Lightning failures. It does not establish this corrected candidate's gates or speed. The new proposal is one24-observation uncapped four-repository-first sequence,12inputs twice,15-second finite cleanup, no retries/profiles/comparators/new repositories/target execution/paid calls. Normal1,800-second product deadline unchanged;181earlier-language observations excluded. ProposalSHA-256 `{binding['proposal_sha256']}`. No approval or token exists and zero current-source observations ran.

Phase22remains incomplete pending actual gates, explicit human technical acceptance and accepted closeout. V68performance proposal remains unapproved/unimplemented. Git312/1,040incomplete; paid benchmark/pilots deferred, Phase21incomplete, Phase24/15unchanged. No merge, ready-state, release, outreach or Phase23.
'''
for a,b in [('unapproved24','unapproved 24'),('passes2,','passes 2,'),('all12hosted','all 12 hosted'),('all29normal','all 29 normal'),('coverage{','coverage {'),('coverage'+f"{cov['percent_covered']:.2f}",'coverage '+f"{cov['percent_covered']:.2f}"),('branch-only'+f"{cov['percent_branches_covered']:.2f}",'branch-only '+f"{cov['percent_branches_covered']:.2f}"),('and19runtime','and 19 runtime'),('All407requirements','All 407 requirements'),('previous4145','previous 4145'),('remains24complete/12equal','remains 24 complete / 12 equal'),('one24-observation','one 24-observation'),('sequence,12inputs twice,15-second','sequence, 12 inputs twice, 15-second'),('Normal1,','Normal 1,'),(';181earlier-language','; 181 earlier-language'),('ProposalSHA','Proposal SHA'),('Phase22remains','Phase 22 remains'),('V68performance','V68 performance'),('Git312/1,040incomplete','Git 312/1,040 incomplete'),('Phase21incomplete','Phase 21 incomplete'),('Phase24/15unchanged','Phase 24/15 unchanged'),('Phase23','Phase 23')]:body=body.replace(a,b)
with (out/'pr-body.md').open('x') as f:f.write(body)
print('Rendered actual correction, initial failures and unapproved24-observation scope;407requirements retained.')
